INSERT INTO `bestemmingen` (`Bestemmingcode`, `Plaats`, `Land`, `Werelddeel`) VALUES 
('ALANY', 'Alanya', 'Turkije', 'West-Europa'),
('ALEXA', 'Alexandrie', 'Egypte', 'Afrika'),
('ANTAL', 'Antalya', 'Turkije', 'West-Europa'),
('BAGHD', 'Baghdad', 'Irak', 'Azie'),
('BALI', 'Bali', 'Indonesie', 'Azie'),
('BANGK', 'Bangkok', 'Thailand', 'Azie'),
('BARCE', 'Barcelona', 'Spagne', 'West-Europa'),
('BASRA', 'Basra', 'Irak', 'Azie'),
('BENID', 'Benidorm', 'Spagne', 'West-Europa'),
('BOGOT', 'Bogota', 'Colombia', 'Zuid-Amerika'),
('BUENO', 'Buenos Aires', 'Argentinie', 'Zuid-Amerika'),
('CAIRO', 'Cairo', 'Egypte', 'Afrika'),
('CALGA', 'Calgary', 'Canada', 'Noord-Amerika'),
('CARAC', 'Caracas', 'Venezuela', 'Zuid-Amerika'),
('CARTA', 'Cartagena', 'Colombia', 'Zuid-Amerika'),
('CASSA', 'Cassablanca', 'Marokko', 'Afrika'),
('CHIAN', 'Chianmai', 'Thailand', 'Azie'),
('CORDO', 'Cordoba', 'Argentinie', 'Zuid-Amerika'),
('CORSI', 'Corsica', 'Frankrijk', 'West-Europa'),
('DALLA', 'Dallas', 'Verenigde Staten', 'Noord-Amerika'),
('DROME', 'Drome', 'Frankrijk', 'West-Europa'),
('DUSSD', 'Dusseldorf', 'Duitsland', 'West-Europa'),
('ELALA', 'El''Alamein', 'Egypte', 'Afrika'),
('GERON', 'Gerona', 'Spagne', 'West-Europa'),
('GITES', 'Gites', 'Frankrijk', 'West-Europa'),
('GRANC', 'Gran Canaria', 'Spagne', 'West-Europa'),
('HELSI', 'Helsinki', 'Finland', 'West-Europa'),
('ISTAN', 'Istanbul', 'Turkije', 'West-Europa'),
('JAKAR', 'Jakarta', 'Indonesie', 'Azie'),
('KIRKU', 'Kirkuk', 'Irak', 'Azie'),
('LIMA', 'Lima', 'Peru', 'Zuid-Amerika'),
('MADRI', 'Madrid', 'Spagne', 'West-Europa'),
('MANIL', 'Manila', 'Filippijnen', 'Azie'),
('MARDE', 'Mar del Plata', 'Argentinie', 'Zuid-Amerika'),
('MEDAN', 'Medan', 'Indonesie', 'Azie'),
('MEXIC', 'Mexico', 'Mexico', 'Noord-Amerika'),
('MIAMI', 'Miami', 'Verenigde Staten', 'Noord-Amerika'),
('MOIRA', 'Moirara', 'Spagne', 'West-Europa'),
('MONTE', 'Montevideo', 'Uruguay', 'Zuid-Amerika'),
('MONTR', 'Montreal', 'Canada', 'Noord-Amerika'),
('MOSUL', 'Mosul', 'Irak', 'Azie'),
('NEWOR', 'New Orleans', 'Verenigde Staten', 'Noord-Amerika'),
('OTTAW', 'Ottawa', 'Canada', 'Noord-Amerika'),
('PARIJ', 'Parijs', 'Frankrijk', 'West-Europa'),
('PATTA', 'Pattaya', 'Thailand', 'Azie'),
('RABAT', 'Rabat', 'Marokko', 'Afrika'),
('RECIF', 'Recife', 'Brazilie', 'Zuid-Amerika'),
('RIO', 'Rio de Janeiro', 'Brazilie', 'Zuid-Amerika'),
('SALOU', 'Salou', 'Spagne', 'West-Europa'),
('SANFR', 'San Francisco', 'Verenigde Staten', 'Noord-Amerika'),
('SANPA', 'San Pablo', 'Filippijnen', 'Azie'),
('SAOPA', 'Sao Paulo', 'Brazilie', 'Zuid-Amerika'),
('SURUB', 'Surubaya', 'Indonesie', 'Azie'),
('TANGE', 'Tanger', 'Marokko', 'Afrika'),
('THEBE', 'Thebes', 'Egypte', 'Afrika'),
('VERAC', 'Veracruz', 'Mexico', 'Noord-Amerika'),
('WASHI', 'Washington', 'Verenigde Staten', 'Noord-Amerika');